version: "3"
services:
  postgres:
    image: postgres
    container_name: chess_postgres
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - chess_postgres:/var/lib/postgresql/data

  uwsgi:
    build: ./uwsgi
    container_name: chess_uwsgi
    environment:
      DEBUG: "${DEBUG}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
    command: ["bash", "./wait-for-it.sh", "-t", "0", "postgres:5432", "--", "bash", "./entrypoint_uwsgi.sh"]
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./uwsgi:/app
volumes:
  chess_postgres: {}